---

scala:
  version: "2.11.8"
  release_url: "https://downloads.lightbend.com"

#need this to be a separate variable to avoid recursion error 
scala_minor_version: "{{ scala.version | regex_replace('^([0-9]+)\\.([0-9]+)\\..*', '\\1\\.\\2')}}"


spark:
  version: "2.3.3"
  release_url: "http://apache.is.co.za/spark/"
  master_address: 10.0.0.5

ulimit:
  soft: 65536
  hard: 65536
