---

scala:
  version: "2.11.8"
  release_url: "https://downloads.lightbend.com"

#need this to be a separate variable to avoid recursion error 
scala_minor_version: "{{ scala.version | regex_replace('^([0-9]+)\\.([0-9]+)\\..*', '\\1\\.\\2')}}"

spark:
  version: "2.1.0"

ulimit:
  soft: 65536
  hard: 65536

