---

# Changing Ulimit configuration - allow Cassandra to have more files open than the default
- name: 'Ulimit'
  include: ulimit.yml
  when: ulimit is defined

- name: 'Install dns utils'
  include: dns.yml

- name: 'LogRotate'
  include: logrotate.yml

- name: 'Install Common Tools'
  include: tooling.yml

# Cassandra nodes should run with clocks in sync - set up NTP for that
- name: 'Install NTP Configuration'
  include: ntp.yml
