---

- name: 'Install utility: tcpdump'
  become: true
  yum: name='tcpdump' state='present'
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: 'Install utility: lsof'
  become: true
  yum: name='lsof' state='present'
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: 'Install utility: rsync'
  become: true
  yum: name='rsync' state='present'
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: 'Install utility: nmap'
  become: true
  yum: name='nmap' state='present'
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: 'Install utility: deltarpm'
  become: true
  yum: name='deltarpm' state='present'
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
 
- name: 'Install wget'
  become: yes
  yum: name='wget'  state='present'
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: 'Install utility: tcpdump'
  become: true
  apt: name='tcpdump' state='present'
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: 'Install utility: lsof'
  become: true
  apt: name='lsof' state='present'
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: 'Install utility: rsync'
  become: true
  apt: name='rsync' state='present'
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: 'Install utility: nmap'
  become: true
  apt: name='nmap' state='present'
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: 'Install utility: deltarpm'
  become: true
  apt: name='deltarpm' state='present'
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
 
- name: 'Install wget'
  become: yes
  apt: name='wget'  state='present'
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  

