---
# Changing Ulimit configuration - allow to have more files open than the default
- name: 'Create ulimit configuration'
  become: yes
  template:
    src: 'ulimit.conf.j2'
    dest: '/etc/security/limits.conf'
