---
- name: Install spark slave service
  become: yes
  template:
    src: templates/spark-slave.service.j2
    dest: /etc/systemd/system/spark-slave.service
    mode: 0644 
  notify: restart spark-slave    

